apiVersion: v1
kind: Namespace
metadata:
  name: social-live-backend
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: social-live-frontend
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: social-live-streaming
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: social-live-monitoring
  labels:
    istio-injection: enabled